#!/bin/bash
# Daily news-agent pipeline.
# Triggered by launchd; can also be run manually for testing.
#
# Pipeline:
#   1. fetch_feeds.py     RSS pull, junk filter, cross-day dedup -> raw_items.json
#   2. rank.py            Claude picks top 30 by impact          -> ranked.json
#   3. scrape_content.py  fetch full body for top 30             -> enriched.json
#   4. summarize.py       Claude writes summary + key points     -> digest.json
#   5. render_md.py       generate Markdown                      -> digests/, README.md
#   6. git add (allowlist) + commit + push
#
# Safety: the script will REFUSE to commit if any file outside the
# explicit allowlist is staged.

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_DIR"

# Activate the pyenv-virtualenv specified in .python-version.
# We do NOT rely on `pyenv init` / `pyenv virtualenv-init` here — those
# depend on shell hooks that don't fire in launchd's non-interactive
# context, so `python` would resolve to the base shim instead of the
# venv. Instead, construct the venv's bin dir directly and prepend.
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

VENV_NAME=$(tr -d '[:space:]' < .python-version 2>/dev/null || true)
if [ -z "$VENV_NAME" ]; then
    echo "ERROR: .python-version not found or empty" >&2
    exit 1
fi
VENV_PREFIX=$(pyenv prefix "$VENV_NAME")
export PATH="$VENV_PREFIX/bin:$PATH"
export VIRTUAL_ENV="$VENV_PREFIX"

mkdir -p logs
LOG_FILE="logs/$(date +%Y-%m-%d).log"
exec > >(tee -a "$LOG_FILE") 2>&1

echo
echo "==== news-agent run: $(date) ===="
echo "Python: $(which python) ($(python --version))"

# Pipeline.
python src/fetch_feeds.py
python src/rank.py
python src/scrape_content.py
python src/summarize.py
python src/render_md.py

# Stage ONLY the allowlisted output paths. Never `git add -A`.
# README.md is static (not regenerated by the pipeline); intentionally excluded.
git add digests/ published_links.json

# Hard safety: bail if anything else snuck into the index.
unexpected=$(git diff --cached --name-only \
    | grep -v -E '^(digests/|published_links\.json$)' || true)
if [ -n "$unexpected" ]; then
    echo "ERROR: unexpected staged files, refusing to commit:" >&2
    echo "$unexpected" >&2
    exit 1
fi

DATE=$(date +%Y-%m-%d)
if git diff --cached --quiet; then
    echo "No changes to commit"
else
    git commit -m "Daily digest $DATE"
    git push
    echo "Pushed."
fi

echo "==== news-agent run finished: $(date) ===="
